CALL data_fill();
CALL schedule_maker();

SELECT * FROM bank_accounts;
SELECT * FROM beach_prices;
SELECT * FROM beaches;
SELECT * FROM cars;
SELECT * FROM cashbox_checks;
SELECT * FROM cashboxes;
SELECT * FROM check_statuses;
SELECT * FROM check_types;
SELECT * FROM commissions;
SELECT * FROM copero_payments;
SELECT * FROM coperos;
SELECT * FROM event_logs;
SELECT * FROM event_types;
SELECT * FROM ingredients;
SELECT * FROM ingredients_per_products;
SELECT * FROM inventories;
SELECT * FROM inventory_checks;
SELECT * FROM invoice_details;
SELECT * FROM invoices;
SELECT * FROM levels;
SELECT * FROM object_types;
SELECT * FROM orders;
SELECT * FROM price_logs;
SELECT * FROM products;
SELECT * FROM schedules;
SELECT * FROM sources;
SELECT * FROM users;